model_path: "mix_tangshi/merged"  # Replace with your model path
prompt: | 
  <s>[INST]你是一个唐诗助手,帮助用户写一首对应要求的唐诗 作者:李白
  标签:五言绝句;宫怨[/INST]
# prompt: |
#   <|im_start|>system
#   你是一个唐诗助手,帮助用户写一首对应要求的唐诗<|im_end|>
#   <|im_start|>user
#   作者:李白
#   标签:五言绝句;宫怨<|im_end|>
#   <|im_start|>assistant